version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_northwind
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'your_strong_password_here' # โปรดเปลี่ยนรหัสผ่านนี้
      MYSQL_DATABASE: 'northwind'
    ports:
      - "3306:3306"
    command: --innodb_buffer_pool_size=1G
    volumes:
      - ./northwind.sql:/docker-entrypoint-initdb.d/1-northwind.sql
      - ./init-user.sql:/docker-entrypoint-initdb.d/2-init-user.sql
      - mysql_data:/var/lib/mysql

  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabase-workshop
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_JETTY_PORT: 3000
    restart: unless-stopped

volumes:
  mysql_data:
  metabase-data:
